name: Approvals notification

on:
  pull_request_review:
    types: [submitted]

jobs:
  count_approvals:
    if: github.event.review.state == 'approved' && contains(github.event.pull_request.body, 'Project Abstract')
    runs-on: ubuntu-latest
    outputs:
      required: ${{ steps.required.outputs.required }}
      approved: ${{ steps.reviews.outputs.approved }}
    steps:
      - run: echo 'APPROVALS=?' >> $GITHUB_ENV
      - if: contains(github.event.pull_request.body, '[x] **Level 1**')
        run: echo 'APPROVALS=2' >> $GITHUB_ENV
      - if: contains(github.event.pull_request.body, '[x] **Level 2**')
        run: echo 'APPROVALS=3' >> $GITHUB_ENV
      - if: contains(github.event.pull_request.body, '[x] **Level 3**')
        run: echo 'APPROVALS=5' >> $GITHUB_ENV
      - id: 'required'
        run: echo "required=$APPROVALS" >> $GITHUB_OUTPUT
      - id: 'reviews'
        uses: 'jrylan/github-action-reviews-counter@main'
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'

  send_matrix_approved_msg:
    needs: count_approvals
    uses: ./.github/workflows/matrix-notify.yml
    secrets: inherit
    with:
      message: |
        PR APPROVED: [${{ github.event.pull_request.title }}](https://github.com/w3f/Grants-Program/pull/${{ github.event.pull_request.number }}) has been approved by ${{ github.event.review.user.login }}. 
        Approvals: ${{ needs.count_approvals.outputs.approved }}/${{ needs.count_approvals.outputs.required }}
