name: Ready for Review notification

on:
  pull_request_target:
    types: [ready_for_review]

jobs:
  send_matrix_review_msg:
    uses: ./.github/workflows/matrix-notify.yml
    secrets: inherit
    with:
      message: |
        PR READY FOR REVIEW: [${{ github.event.pull_request.title }}](https://github.com/w3f/Grants-Program/pull/${{ github.event.pull_request.number }}) is ready for review. Labeled by ${{ github.event.sender.login }};
